- .expo/packager-info.json
- .expo/settings.json
- .vscode/settings.json
- Fire.js
- package-lock.json
- package.json
- Please delete package lock and npm install dependencies again for most updated versions
- new firebase config; please fall back on previous if anything breaks
> updated dependencies, firebase config

- .expo/packager-info.json
- Fire.js
- components/Signup.js
> enforce unique username

- .expo/packager-info.json
- Fire.js
- components/ChatRoom.js
- components/SlackBubble.js
Revised chatroom so that on initial render, only the first 10 messages are grabbed form the database. Users can then scroll up and then new messages will append automatically, making fir a seamless scroll.
> Load earlier

- .expo/packager-info.json
- Fire.js
- components/ChatList.js
- components/ChatRoom.js
- components/Home.js
- components/Login.js
- components/Signup.js
- components/SlackBubble.js
- package-lock.json
- package.json
Upload images is complete locally, but is not working once deployed. I have isolated the issue and see how to fix it but will not have time to finish it tonight. I am making this pull request because is has some styling stuff as well and it won't actually break anything - so in case we are deploying before I get to finish this issue. NPM install to ensure you have all the updated libraries. I will continue working on this issue tomorrow.
> Upload images

- .expo/packager-info.json
- Fire.js
Adding new room - render automatically on chat list view.
> fix addnew thread

- .expo/packager-info.json
- .expo/settings.json
- Fire.js
- components/ChatRoom.js
- components/Login.js
- components/Signup.js
- components/SlackBubble.js
- modified the sign in page with link to EULA
- modified login page with link to EULA
- added directions to top of chat instructing users to long press and swipe back to return to home
- added the groundwork for the flag icon <-- still needs completion
> adding EULA

- .expo/packager-info.json
- .expo/settings.json
- Fire.js
- components/ChatList.js
- components/ChatRoom.js
- components/SlackBubble.js
Add leave room event which triggers a change in online users count to a chatroom for app inactivity, metro bundler errors that kick a users out of the app, and when a user navigates into PM. 
We might need to update this feature as we come across more edge cases.
> Online users

- Fire.js
- components/ChatList.js
- components/Home.js
- components/Login.js
> Add chat fix+password reset

- .expo/packager-info.json
- .expo/settings.json
- app.json
- components/Navbar.js
- components/Signup.js
- package-lock.json
- package.json
- yarn.lock
- quick fix for typo in Signup.js, line 211 that causes a global red screen error
- skeleton code for footer navbar added as well, not finished but no errors
> fixing error-causing typo

- .expo/packager-info.json
- components/Signup.js
Switched signup popup from modal to native alert
> Signup popup

- .expo/packager-info.json
- .expo/settings.json
- components/SlackBubble.js
- changed SlackBubble line 180 that was causing an error
> changed username issue that was causing an error

- .expo/packager-info.json
- .expo/settings.json
- components/AllReplies.js
- components/ChatRoom.js
- components/SlackBubble.js
- message text still doesn't wrap under username (still not sure whether that's possible)
- message width is 300 for original posts and 200 for replies to prevent continuing outside screen (flexWrap doesn't seem to work)
> username and message on same line formatting

- .expo/packager-info.json
- App.js
- Fire.js
- components/BackButton.js
- components/ChatRoom.js
- components/Navbar.js
- fix date bug in live chat for month and for time
- conditional rendering for chatroom subtitles
> fix date bug in live chat for month and for time, conditional rendering subtitles

- .expo/packager-info.json
- .expo/settings.json
- components/ChatRoom.js
- components/PartnerList.js
- package-lock.json
- package.json
- password modal, rudiments of conditional rendering for passcode icon
> password modal, rudiments of conditional rendering for passcode icon

- .expo/packager-info.json
- Fire.js
- components/PartnerList.js
Still have to check whether unlocking one partner once actually gets stored in the db
> Partner passwords

- .expo/packager-info.json
- App.js
- components/PartnerList.js
- conditional rendering of locks based on locked/unlocked status is successful 
- newly unlocked chats are pushed to unlockedPartners node successfully 
- successfully unlocked chats navigate to correct partner boards list 
- passwords are successfully accessed for each mapped partner 
- hid status bar (battery percent, etc.)
- n.b. there are a lot of console.logs that can be commented out
> finished PartnerList

- .expo/packager-info.json
- .expo/settings.json
- App.js
- components/CategoryList.js
- components/ChatList.js
- rudiments of categories page
> rudiments of categories page

- .expo/packager-info.json
- .expo/settings.json
- Fire.js
- components/ChatList.js
- choosing a category filters the chatrooms by category
> filter chatlist by category

- .expo/packager-info.json
- .expo/settings.json
- App.js
- assets/icons/ChevronIcon.js
- assets/icons/InfoIcon.js
- components/CategoryList.js
- components/ChatList.js
- components/ChatRoom.js
- components/Home.js
- components/Login.js
- components/Navbar.js
- components/PMList.js
- components/PartnerList.js
- components/Resources.js
- components/UserPage.js
- category toggle descriptions
- change margin for help icon to lower
- still need to toggle per button and not for entire page
> category toggle descriptions, change margin for help icon to lower

- .expo/packager-info.json
- .expo/settings.json
- Fire.js
- components/CategoryList.js
- components/SlackBubble.js
- package.json
- pressing the (i) icon in category list displays info for the selected category
- fixed bracket spacing issue with prettier
> Toggle categories

- .expo/packager-info.json
- .expo/settings.json
- components/CategoryList.js
- add touchable opacity to chevron icon
> linking chevron

- .expo/packager-info.json
- .expo/settings.json
- Fire.js
- components/BookmarkListIcon.js
- components/ChatList.js
- components/PMList.js
- components/Signup.js
- components/SlackBubble.js
- components/UserPage.js
- users in DB should be deleted and recreated to keep data consistent
- users whose key is a name instead of ID number will not have a smooth user experience
> Identify users by uid

- .expo/packager-info.json
- .expo/settings.json
- components/SlackBubble.js
- reactions also work for replies
> reaction icons change to dark gray when count is greater than 0

- .expo/packager-info.json
- .expo/settings.json
- App.js
- Fire.js
- Utilities.js
- components/ChatList.js
- components/Home.js
- components/Navbar.js
- components/PartnerList.js
- package-lock.json
- package.json
Upon loading home component:
-- run check to see current day and time
-- put on state day and time of nearest chat
-- agree to get notifications and store notification token
-- subscribe to notifications (if app is foregrounded when notification comes in, pop up an alert)
-- schedule notification with the nearest chat (from state)
-- update state for next week
-- every week repeat last two steps
> Live chat notifs

- .expo/packager-info.json
- .expo/settings.json
- Fire.js
- components/Navbar.js
- components/PartnerList.js
- components/SlackBubble.js
- components/SlackMessage.js
- PMs display date above messages and timestamps in parentheses next to usernames, does not display entry/exit stamps
- live chat displays entry/exit stamps and timestamps next to usernames
> PM and live chat time stamps

- .expo/packager-info.json
- .expo/settings.json
- Fire.js
- components/Navbar.js
- components/SlackBubble.js
- replying to a reply results in a new reply to the parent message, prepended with a mention of the person being replied to
- message text styling can be directly modified, however the text doesn't wrap properly
> Mentions from replies

- .expo/packager-info.json
- .expo/settings.json
- Fire.js
- components/Navbar.js
- components/SlackBubble.js
- reactions now work in all 3 different types of rooms (live, pm, category chat)
- 'getRoomType' function created in SlackBubble to facilitate this
- reactions work with new single-level of nesting reply structure
> reactions work in PMrooms chatrooms and live chat

- components/AllReplies.js
- components/SlackBubble.js
- components/SlackMessage.js
- replies to replies now render immediately when added
> Fixes Issue 224
